INSERT INTO "actions" VALUES(1,'CAL','Recalibration',1);
INSERT INTO "actions" VALUES(2,'REA','New reagent lot',1);
INSERT INTO "actions" VALUES(3,'MNT','Instrument maintenance',1);
INSERT INTO "actions" VALUES(4,'CTR','New control lot',1);
INSERT INTO "actions" VALUES(5,'REP','Repeated, in control',1);
INSERT INTO "actions" VALUES(6,'NCF','Non conformity opened',1);
INSERT INTO "actions" VALUES(7,'ERR','Entered in error',1);
INSERT INTO "actions" VALUES(8,'DUP','Entered twice',1);
INSERT INTO "categories" VALUES(1,'Antiepileptics',1);
INSERT INTO "categories" VALUES(2,'Immunosuppressants',1);
INSERT INTO "categories" VALUES(3,'Steroid hormones',1);
INSERT INTO "categories" VALUES(4,'Vitamins',1);
INSERT INTO "categories" VALUES(5,'Catecholamines',1);
INSERT INTO "categories" VALUES(6,'Alcohol markers',1);
INSERT INTO "categories" VALUES(7,'Drugs of abuse',1);
INSERT INTO "controls" VALUES(1,2,'MassCheck Antiepileptic Drugs','0250',1);
INSERT INTO "controls" VALUES(2,5,'ClinChek Immunosuppressants','8848',1);
INSERT INTO "controls" VALUES(3,2,'MassChrom Steroids in Serum','6200',1);
INSERT INTO "controls" VALUES(4,4,'Vitamins Control','VT-200',1);
INSERT INTO "controls" VALUES(5,4,'Catecholamines Control','CA-310',1);
INSERT INTO "controls" VALUES(6,4,'CDT Control','CDT-120',1);
INSERT INTO "controls" VALUES(7,2,'MassCheck Drugs of Abuse in Urine','0330',1);
INSERT INTO "controls" VALUES(8,4,'Ethanol Control in Blood','ET-520',1);
INSERT INTO "controls" VALUES(9,3,'Drugs of Abuse in Hair','HR-450',1);
INSERT INTO "controls" VALUES(10,3,'Drugs of Abuse in Blood','BL-460',1);
INSERT INTO "controls" VALUES(11,3,'EtG in Keratin','ETG-610',1);
INSERT INTO "controls" VALUES(12,3,'EtG in Urine','ETG-620',1);
INSERT INTO "equipments" VALUES(1,6,'QTRAP 5500',1);
INSERT INTO "equipments" VALUES(2,6,'QTRAP 6500',1);
INSERT INTO "equipments" VALUES(3,1,'1100 Series HPLC',1);
INSERT INTO "equipments" VALUES(4,1,'7890B GC with 7697A headspace',1);
INSERT INTO "methods" VALUES(1,'LC-MS/MS',1);
INSERT INTO "methods" VALUES(2,'HPLC-UV/VIS',1);
INSERT INTO "methods" VALUES(3,'HS-GC/MS',1);
INSERT INTO "samples" VALUES(1,'Serum',1);
INSERT INTO "samples" VALUES(2,'Whole blood',1);
INSERT INTO "samples" VALUES(3,'Plasma',1);
INSERT INTO "samples" VALUES(4,'Urine',1);
INSERT INTO "samples" VALUES(5,'Keratin',1);
INSERT INTO "samples" VALUES(6,'Blood',1);
INSERT INTO "session" VALUES(1,NULL);
INSERT INTO "suppliers" VALUES(1,'Agilent Technologies',1);
INSERT INTO "suppliers" VALUES(2,'Chromsystems',1);
INSERT INTO "suppliers" VALUES(3,'Comedical',1);
INSERT INTO "suppliers" VALUES(4,'Eureka',1);
INSERT INTO "suppliers" VALUES(5,'Recipe',1);
INSERT INTO "suppliers" VALUES(6,'SCIEX',1);
INSERT INTO "units" VALUES(1,'ug/mL',1);
INSERT INTO "units" VALUES(2,'ng/mL',1);
INSERT INTO "units" VALUES(3,'ug/L',1);
INSERT INTO "units" VALUES(4,'pg/mL',1);
INSERT INTO "units" VALUES(5,'%',1);
INSERT INTO "units" VALUES(6,'pg/mg',1);
INSERT INTO "units" VALUES(7,'g/L',1);
INSERT INTO "users" VALUES(1,'Administrator',NULL,'admin','$2b$12$IVC2qsJbkVBxGi0mrwK/y.LujEPvNVmIfHCn3w5YKKw.CFjXLAmn2',0,1);
